# ================================
# Database Configuration
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hiremate}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# Hibernate / JPA Configuration
# ================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.resources.static-locations=file:uploads/

# ================================
# Server Port
# ================================
server.port=${PORT:8080}

# ================================
# JWT Configuration
# ================================
jwt.expirationMs=86400000
jwt.secret=8d2f9b7c23a745ecb0c94f5f8184f73681dce2a76f71bb6d3f56e7f8715e8cd0