--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Homebrew)
-- Dumped by pg_dump version 17.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: applications; Type: TABLE; Schema: public; Owner: gurmukhsingh
--

CREATE TABLE public.applications (
    id bigint NOT NULL,
    user_id bigint,
    job_id bigint,
    cover_letter text,
    applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(255),
    resume_path character varying(255),
    resume_filename character varying(255)
);


ALTER TABLE public.applications OWNER TO gurmukhsingh;

--
-- Name: applications_id_seq; Type: SEQUENCE; Schema: public; Owner: gurmukhsingh
--

CREATE SEQUENCE public.applications_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.applications_id_seq OWNER TO gurmukhsingh;

--
-- Name: applications_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: gurmukhsingh
--

ALTER SEQUENCE public.applications_id_seq OWNED BY public.applications.id;


--
-- Name: job; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job (
    id bigint NOT NULL,
    description character varying(255),
    location character varying(255),
    title character varying(255)
);


ALTER TABLE public.job OWNER TO postgres;

--
-- Name: job_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: gurmukhsingh
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    employer_id bigint,
    title character varying(100),
    description text,
    salary character varying(255),
    company character varying(255),
    location character varying(255)
);


ALTER TABLE public.jobs OWNER TO gurmukhsingh;

--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: gurmukhsingh
--

CREATE SEQUENCE public.jobs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.jobs_id_seq OWNER TO gurmukhsingh;

--
-- Name: jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: gurmukhsingh
--

ALTER SEQUENCE public.jobs_id_seq OWNED BY public.jobs.id;


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.roles_id_seq OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.roles_id_seq OWNED BY public.roles.id;


--
-- Name: user_job; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_job (
    job_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_job OWNER TO postgres;

--
-- Name: user_job_applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_job_applications (
    user_id bigint NOT NULL,
    job_id bigint NOT NULL
);


ALTER TABLE public.user_job_applications OWNER TO postgres;

--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: gurmukhsingh
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    employer_id bigint,
    role character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO gurmukhsingh;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: gurmukhsingh
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO gurmukhsingh;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: gurmukhsingh
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: applications id; Type: DEFAULT; Schema: public; Owner: gurmukhsingh
--

ALTER TABLE ONLY public.applications ALTER COLUMN id SET DEFAULT nextval('public.applications_id_seq'::regclass);


--
-- Name: jobs id; Type: DEFAULT; Schema: public; Owner: gurmukhsingh
--

ALTER TABLE ONLY public.jobs ALTER COLUMN id SET DEFAULT nextval('public.jobs_id_seq'::regclass);


--
-- Name: roles id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles ALTER COLUMN id SET DEFAULT nextval('public.roles_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: gurmukhsingh
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: gurmukhsingh
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- Name: job job_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: gurmukhsingh
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: users uk_o3gpy7smnab28a60d5aumqphl; Type: CONSTRAINT; Schema: public; Owner: gurmukhsingh
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_o3gpy7smnab28a60d5aumqphl UNIQUE (employer_id);


--
-- Name: roles uk_ofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uk_ofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: user_job_applications user_job_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_job_applications
    ADD CONSTRAINT user_job_applications_pkey PRIMARY KEY (user_id, job_id);


--
-- Name: user_job user_job_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_job
    ADD CONSTRAINT user_job_pkey PRIMARY KEY (job_id, user_id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: gurmukhsingh
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: gurmukhsingh
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: applications applications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: gurmukhsingh
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: applications fk_applications_job; Type: FK CONSTRAINT; Schema: public; Owner: gurmukhsingh
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fk_applications_job FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- Name: user_job_applications fkeiow2rj0vrwmso5y9m1cj7uef; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_job_applications
    ADD CONSTRAINT fkeiow2rj0vrwmso5y9m1cj7uef FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_job_applications fkg8fvaa1kqgnixjs0oigcj447l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_job_applications
    ADD CONSTRAINT fkg8fvaa1kqgnixjs0oigcj447l FOREIGN KEY (job_id) REFERENCES public.job(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_job fkia2o1pm0plymfbt26ps56ox5l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_job
    ADD CONSTRAINT fkia2o1pm0plymfbt26ps56ox5l FOREIGN KEY (job_id) REFERENCES public.job(id);


--
-- Name: user_job fkk21pxmvwnt38pdyav8w30lcjw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_job
    ADD CONSTRAINT fkk21pxmvwnt38pdyav8w30lcjw FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: jobs jobs_employer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: gurmukhsingh
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

